services:
  - type: web
    name: nexus
    runtime: image
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-db
          property: connectionString
      - key: BROADCAST_CONNECTION
        value: pusher
      - key: PUSHER_APP_ID
        value: ton_app_id
      - key: PUSHER_APP_KEY
        value: ton_key
      - key: PUSHER_APP_SECRET
        value: ton_secret
      - key: PUSHER_APP_CLUSTER
        value: ton_cluster
      - key: PUSHER_HOST
        value: 
      - key: PUSHER_PORT
        value: 443
      - key: PUSHER_SCHEME
        value: https
      - key: VITE_PUSHER_APP_KEY
        value: ton_key
      - key: VITE_PUSHER_APP_CLUSTER
        value: ton_cluster
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: nexus-db
    plan: free